#!/bin/bash

#  Copyright © 2023 Thomas A. Early, N7TAE
#
# ----------------------------------------------------------------------------
#    This script is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This script is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    with this software.  If not, see <http:#www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

if (( $# != 3 )); then
	echo Usage: "$0 reflector module (c|e|p|s|u|v|4|6)"
	exit 1
fi

k=${3,,}

if [[ "$k" == c* ]]; then
	p='Country'
elif [[ "$k" == e* ]]; then
	p='Email'
elif [[ "$k" == p* ]]; then
	p='Port'
elif [[ "$k" == s* ]]; then
	p='Sponsor'
elif [[ "$k" == u* ]]; then
	p='URL'
elif [[ "$k" == v* ]]; then
	p='Version'
elif [[ "$k" == 4* ]]; then
	p='IPv4Address'
elif [[ "$k" == 6* ]]; then
	p='IPv6Address'
else
	echo "'$3' is not regcognized! Please use one of:"
	echo "c (for Country)"
	echo "e (for Email)"
	echo "p (for Port)"
	echo "s (for Sponsor)"
	echo "u (for URL)"
	echo "v (for Version)"
	echo "4 (for IPv4Address)"
	echo "6 (for IPv6Address)"
	exit 2
fi

reflectors=( `./dht-spider -l $1 $2` )

for r in ${reflectors[*]}
do
	echo $r `./dht-get -sc $r | jq --raw-output .Configuration.$p`
done

exit 0
