/*
 *   Copyright (c) 2024 by Thomas A. Early N7TAE
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <nlohmann/json.hpp>
#include <curl/curl.h>
#include <opendht.h>
#include <iostream>
#include <sstream>
#include <string>
#include <mutex>
#include <algorithm>
#include <condition_variable>

#include "dht-values.h"
#include "dht-helpers.h"

static const std::string Version("1.3.0");
std::string hostname("xrf757.openquad.net");
static bool got_data;
static bool running;
static std::condition_variable cv;
static std::mutex mtx;
static char section = 'a';
static bool use_local = false;
static dht::Where w;
static SMrefdConfig1  mrefdConfig;
static SUrfdConfig1   urfdConfig;


// callback function writes data to a std::ostream
static size_t data_write(void  *buf, size_t size, size_t nmemb, void *userp)
{
	if(userp)
	{
		std::ostream &os = *static_cast<std::ostream *>(userp);
		std::streamsize len = size * nmemb;
		if(os.write(static_cast<char*>(buf), len))
			return len;
	}

	return 0;
}

/**
 * timeout is in seconds
 **/
static CURLcode curl_read(const std::string& url, std::ostream& os, long timeout = 30)
{
	CURLcode code(CURLE_FAILED_INIT);
	CURL* curl = curl_easy_init();
	const std::string agent(std::string("Ham-DHT/")+Version);

	if(curl)
	{
		if(CURLE_OK == (code = curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &data_write))
		&& CURLE_OK == (code = curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 1L))
		&& CURLE_OK == (code = curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L))
		&& CURLE_OK == (code = curl_easy_setopt(curl, CURLOPT_FILE, &os))
		&& CURLE_OK == (code = curl_easy_setopt(curl, CURLOPT_TIMEOUT, timeout))
		&& CURLE_OK == (code = curl_easy_setopt(curl, CURLOPT_USERAGENT, agent.c_str()))
		&& CURLE_OK == (code = curl_easy_setopt(curl, CURLOPT_URL, url.c_str())))
		{
			code = curl_easy_perform(curl);
		}
		curl_easy_cleanup(curl);
	}
	return code;
}

static bool ReadM17Json(const std::string &url, std::stringstream &ss)
{
	curl_global_init(CURL_GLOBAL_ALL);

	if(CURLE_OK == curl_read(url, ss)) {
		std::cout << "# Copied " << url << std::endl;
	} else {
		std::cout << "# ERROR: Could not copy " << url << std::endl;
		return true;
	}

	curl_global_cleanup();
	return false;
}

std::string comname;

using json = nlohmann::json;
#define GET_STRING(a) ((a).is_string() ? a : "")

static void Usage(std::ostream &ostr)
{
	ostr
	<< std::endl << "Usage: " << comname << " [Option]\n\n"
	<< "There are three mutually exclusive options:\n"
	<< "-b hostname\n"
	<< "   Where 'hostname' is any running node on the Ham-DHT network\n"
	<< "   If not specified, " << hostname << " will be used.\n"
	<< "-v | --version\n"
	<< "   Will print the version and exit.\n"
	<< "-h | --help\n"
	<< "   Will print this usage message and exit." << std::endl;
}

enum class ESource { dvref, dht };
int main (int argc, char *argv[])
{
	comname.assign(argv[0]);
	if (2 == argc)
	{
		const std::string arg(argv[1]);
		if (0 == arg.compare("-v") or 0 == arg.compare("--version"))
		{
			std::cout << "Version #" << Version << std::endl;
			return EXIT_SUCCESS;
		}
		else if (0 == arg.compare("-h") || 0 == arg.compare("--help"))
		{
			Usage(std::cout);
			return EXIT_SUCCESS;
		}
		Usage(std::cerr);
		return EXIT_FAILURE;
	}
	else if (3 == argc)
	{
		const std::string arg(argv[1]);
		if (0 == arg.compare("-b"))
			hostname.assign(argv[2]);
		else
		{
			Usage(std::cerr);
			return EXIT_FAILURE;
		}
	}
	else if (3 < argc)
	{
		Usage(std::cerr);
		return EXIT_FAILURE;
	}

	// boot up the Ham-DTH
	std::string name("GetM17Hosts");
	name += std::to_string(getpid());
	dht::DhtRunner node;
	try {
		node.run(17171, dht::crypto::generateIdentity(name), true, 59973);
		node.bootstrap(hostname, "17171");
	} catch (const std::exception &ex) {
		std::cout << argv[0] << " can't connect to the Ham-DHT! " << ex.what() << std::endl;
		return 1;
	}

	// print the preamble
	auto t = std::time(nullptr);
	auto tm = *std::gmtime(&t);
	std::cout 
	<< "# M17 Hosts file generated by " << comname << " V#" << Version << '\n'
	<< "# Copyright (C) 2024-2026 by Thomas A. Early, N7TAE.\n"
	<< "# See the LICENSE file in https://github.com/n7tae/dht-ham-tools.\n"
	<< "# Created on " << std::put_time(&tm, "%Y-%m-%d at %H:%M GMT") << std::endl;

	// downlaod and parse the mrefd and urf json file
	std::stringstream ss;
	if (ReadM17Json("https://hostfiles.refcheck.radio/M17Hosts.json", ss))
	{
		std::cerr << "ERROR curling M17 reflectors from hostfiles.refcheck.radio/M17Hosts.json" << std::endl;
		return 1;
	}

	json mref;

	try {
		mref = json::parse(ss.str());
	}
	catch (const std::exception &e) {
		std::cerr << "ERROR: " << e.what() << std::endl;
		return 1;
	}
	
	if (not mref.contains("reflectors"))
	{
		std::cerr << "ERROR: the json file contains no reflectors" << std::endl;
		return 1;
	}

	std::cout
	<< "# WARNING: Reflectors without a version strings are not using the Ham-DHT and\n"
	<< "# might have UNKNOWN capabilities and/or incorrect data.\n"
	<< "# These are input by hand by the admin and might be INCORRECT.\n"
	<< "# It is assumed that reflectors without a version string are version 0.x.y\n"
	<< "# You can edit any of these values if you know what they are.\n"
	<< "#\n"
	<< "# An empty 'IPv4-address' or 'IPv6-address' means it's not configured.\n"
	<< "# An empty 'Modules' means it can't be determined and it won't be added.\n"
	<< "#\n"
	<< "# 'Special-modules' for M17 reflectors will pass encrypted voice data.\n"
	<< "# 'Special-modules' for URF reflectors are fully transcoded.\n"
	<< "#\n"
	<< "#Reflector;Version;Modules;Special-modules;IPv4-address;IPv6-address;Port;Dashboard-URL\n";

	w.id(toUType(EMrefdValueID::Config));
	// iterate through reflectors array
	for (auto &ref : mref["reflectors"])
	{
		running = true;
		got_data = false;
		std::string cs(ref["designator"].get<std::string>());
		std::string ipv4(GET_STRING(ref["ipv4"]));
		std::string ipv6(GET_STRING(ref["ipv6"]));
		ESource src = ESource::dvref;
		std::string version;
		std::string mods, smods;
		uint16_t port = 17000;
		std::string url(GET_STRING(ref["url"]));
		auto keyhash = dht::InfoHash::get(cs);
		if (0 == cs.substr(0,4).compare("M17-"))
		{
			if (ref.contains("modules")) {
				for (auto &mod : ref["modules"])
					mods.append(GET_STRING(mod));
			}
			if (mods.size() > 1)
				std::sort(mods.begin(), mods.end());
			if (ref.contains("encrypted")) {
				for (auto &mod : ref["encrypted"])
					smods.append(GET_STRING(mod));
			}
			if (smods.size() > 1)
				std::sort(smods.begin(), smods.end());
			if (ref.contains("port") and ref["port"].is_number_unsigned())
				port = ref["port"].get<uint16_t>();
			mrefdConfig.timestamp = 0;
			node.get(
				keyhash,
				[](const std::shared_ptr<dht::Value> &v) {
					if (v->checkSignature())
					{
						switch (v->id)
						{
							case toUType(EMrefdValueID::Config):
								if (0 == v->user_type.compare(MREFD_CONFIG_1))
								{
									got_data = true;
									auto rdat = dht::Value::unpack<SMrefdConfig1>(*v);
									if (rdat.timestamp > mrefdConfig.timestamp)
										mrefdConfig = dht::Value::unpack<SMrefdConfig1>(*v);
								}
								break;
						}
					}
					else
					{
						std::cerr << "Value signature failed!" << std::endl;
					}
					return true;
				},
				[](bool success) {
					if (! success)
						std::cout << "get() unsuccessful!" << std::endl;
					std::unique_lock<std::mutex> lck(mtx);
					running = false;
					cv.notify_all();
				},
				{},	// empty filter
				w
			);

			// wait for node.get()
			std::unique_lock<std::mutex> lck(mtx);
			while (running)
			{
				cv.wait(lck);
			}

			if (got_data)
			{
				version.assign(mrefdConfig.version);
				if (mrefdConfig.ipv4addr.size())
					ipv4.assign(mrefdConfig.ipv4addr);
				if (mrefdConfig.ipv6addr.size())
					ipv6.assign(mrefdConfig.ipv6addr);
				if (mrefdConfig.modules.size())
					mods.assign(mrefdConfig.modules);
				if (mrefdConfig.encryptedmods.size())
					smods.assign(mrefdConfig.encryptedmods);
				if (mrefdConfig.url.size())
					url.assign(mrefdConfig.url);
				port = mrefdConfig.port;
				src = ESource::dht;
			}
		}
		else if (0 == cs.substr(0,3).compare("URF"))
		{
			// fish out the modules and transcoded modules
			if (ref.contains("modules"))
			{
				for (auto &mod : ref["modules"])
				{
					auto m = mod["module"].get<std::string>();
					const std::string mode(GET_STRING(mod["mode"]));
					if (0==mode.compare("All") or 0==mode.compare("M17"))
					{
						mods.append(m);
						if (mod["transcode"].is_boolean())
						{
							if (mod["transcode"].get<bool>())
								smods.append(m);
						}
						if (0 == mode.compare("M17"))
						{
							if (mod["port"].is_number_unsigned())
								port = mod["port"].get<uint16_t>();
						}
					}
				}
			}
			url.assign(GET_STRING(ref["url"]));
			auto keyhash = dht::InfoHash::get(cs);
			urfdConfig.timestamp = 0;
			node.get(
				keyhash,
				[](const std::shared_ptr<dht::Value> &v) {
					if (v->checkSignature())
					{
						switch (v->id)
						{
						case toUType(EUrfdValueID::Config):
							if (0 == v->user_type.compare(URFD_CONFIG_1))
							{
								got_data = true;
								auto rdat = dht::Value::unpack<SUrfdConfig1>(*v);
								if (rdat.timestamp > urfdConfig.timestamp)
									urfdConfig = dht::Value::unpack<SUrfdConfig1>(*v);
							}
						}
					}
					else
					{
						std::cerr << "Value signature failed!" << std::endl;
					}
					return true;
				},
				[](bool success) {
					if (! success)
						std::cout << "get() unsuccessful!" << std::endl;
					std::unique_lock<std::mutex> lck(mtx);
					running = false;
					cv.notify_all();
				},
				{},	// empty filter
				w
			);

			// wait for node.get()
			std::unique_lock<std::mutex> lck(mtx);
			while (running)
			{
				cv.wait(lck);
			}

			if (got_data)
			{
				version.assign(urfdConfig.version);
				if (urfdConfig.ipv4addr.size())
					ipv4.assign(urfdConfig.ipv4addr);
				if (urfdConfig.ipv6addr.size())
					ipv6.assign(urfdConfig.ipv6addr);
				if (urfdConfig.modules.size())
					mods.assign(urfdConfig.modules);
				if (urfdConfig.transcodedmods.size())
					smods.assign(urfdConfig.transcodedmods);
				port = urfdConfig.port[toUType(EUrfdPorts::m17)];
				src = ESource::dht;
				if (urfdConfig.url.size())
					url.assign(urfdConfig.url);
			}
		}
		else
		{
			std::cout << "# Don't know how to parse a '" << cs << "' reflector!" << std::endl;
		}

		if (0 == port)
			continue;
		if (0 == ipv4.compare("127.0.0.1") || 0 == ipv4.compare("0.0.0.0") || 0 == ipv6.compare("::1") || 0 == ipv6.compare("::"))
			continue;

		if (0 == url.compare("https://YourDashboard.net"))
			url.clear();

		if (mods.empty())
			continue;

		std::cout << cs << ';' << version << ';' << mods << ';' << smods << ';' << ipv4 << ';' << ipv6 << ';' << port << ';' << url << '\n';
	}

	node.join(); // disconnect from the Ham-DHT

	std::cout << "\n\n"
	<< "# ################## Direct Routing Targets ##################\n"
	<< "#\n"
	<< "# You do not link to these target, but you load them the same way you link to a reflector:\n"
	<< "# Put the destination in DST and quick-key.\n"
	<< "# Capabilities: 2 chars:\n"
	<< "# 1. Data handling:\n"
	<< "#    'S' if only stream data is processed\n"
	<< "#    'P' if only packet data is processed\n"
	<< "#    'B' if both packet and stream data is processed\n"
	<< "# 2. TYPE handling:\n"
	<< "#    'L' if only legacy TYPE format is used\n"
	<< "#    '3' if only M17 Specification V#3 TYPE format is used\n"
	<< "#    'B' if both formats are understood\n"
	<< "# The example shows that N0CALL will only receive Stream data at 44.46.48.201:17100, and uses the legacy TYPE format\n"
	<< "# NOCALL:SL;44.46.48.201;;17100\n"
	<< "# Destination;Capabilities;IPv4Address;IPv6Address;Port\n";

	return EXIT_SUCCESS;
}
